Repository ethanwharris/gnome-nvidia-extension, pull requests merged in 2022-04, with the labels that each got.

#196 Codebase cleanup
  .eslintrc.yml
  .github/CODE_OF_CONDUCT.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/reuse.yml
  .github/workflows/reviewdog.yml
  .gitignore
  LICENSES/CC-BY-4.0.md
  LICENSES/CC0-1.0.md
  LICENSES/GPL-3.0-or-later.md
  LICENSES/LGPL-2.0-or-later.md
  LICENSES/MIT.txt
  Makefile
  README.md
  screenshot.png.license
  src/nvidiautil@ethanwharris/LICENSE
  src/nvidiautil@ethanwharris/extension.js
  src/nvidiautil@ethanwharris/formatter.js
  src/nvidiautil@ethanwharris/gIcons.js
  src/nvidiautil@ethanwharris/icons/card-symbolic.svg
  src/nvidiautil@ethanwharris/icons/cog-symbolic.svg
  src/nvidiautil@ethanwharris/icons/fan-symbolic.svg
  src/nvidiautil@ethanwharris/icons/power-symbolic.svg
  src/nvidiautil@ethanwharris/icons/ram-symbolic.svg
  src/nvidiautil@ethanwharris/icons/temp-symbolic.svg
  src/nvidiautil@ethanwharris/icons/wrench-symbolic.svg
  src/nvidiautil@ethanwharris/metadata.json
  src/nvidiautil@ethanwharris/metadata.json.license
  src/nvidiautil@ethanwharris/optimusProvider.js
  src/nvidiautil@ethanwharris/prefs.js
  src/nvidiautil@ethanwharris/processor.js
  src/nvidiautil@ethanwharris/processorHandler.js
  src/nvidiautil@ethanwharris/property.js
  src/nvidiautil@ethanwharris/schemas/gschemas.compiled.license
  src/nvidiautil@ethanwharris/schemas/org.gnome.shell.extensions.nvidiautil.gschema.xml
  src/nvidiautil@ethanwharris/settingsAndSmiProvider.js
  src/nvidiautil@ethanwharris/settingsProperties.js
  src/nvidiautil@ethanwharris/settingsProvider.js
  src/nvidiautil@ethanwharris/smiProperties.js
  src/nvidiautil@ethanwharris/smiProvider.js
  src/nvidiautil@ethanwharris/stylesheet.css
  src/nvidiautil@ethanwharris/subprocess.js
Labels: enhancement, needs review, gnome40

#200 Fix version 9 review issues
  src/nvidiautil@ethanwharris/extension.js
  src/nvidiautil@ethanwharris/gIcons.js
  src/nvidiautil@ethanwharris/settingsProperties.js
  src/nvidiautil@ethanwharris/smiProperties.js
Labels: bug, needs review

#201 update for gnome 42 compatibility
  src/nvidiautil@ethanwharris/metadata.json
Labels: hotfix
